spring:
  application:
    name: zuul-server
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8507/
server:
  port: 8054
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8501/eureka/
zuul:
  routes:
    test:
      path: /test/**
      url: http://www.google.com

